name: flutter_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.6
  path: ^1.8.1
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  pie_chart: ^5.4.0
  slide_digital_clock: ^1.0.3
#  google_maps_flutter: ^2.2.1
  location: ^5.0.3
  #  geolocator: ^9.0.1
  image: ^4.2.0
  go_router: ^14.1.0
  hooks_riverpod: ^2.5.1
  fpdart: ^1.1.0
  http: ^1.2.1
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.0
  crypto: ^3.0.3
  flutter_speed_dial: ^6.0.0
  animated_bottom_navigation_bar: ^1.3.3
  carousel_slider: ^4.0.0
  loading_animation_widget: ^1.2.1
  smooth_page_indicator: ^1.1.0
  rflutter_alert: ^2.0.7
  provider: ^6.1.2
  table_calendar: ^3.0.0
  calendar_date_picker2: ^1.0.0
  file_picker: ^5.0.1
  floating_action_bubble: ^1.1.4
  flutter_svg: ^2.0.9
  camera_camera: ^3.0.0
  progress_stepper: ^3.1.0
  image_picker: ^1.1.2
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.8
  video_player: ^2.2.11
  flick_video_player: ^0.9.0
  appinio_video_player: ^1.2.0
  dynamic_tabbar: ^1.0.7
  chewie: ^1.2.2
  font_awesome_flutter: ^10.1.0
  awesome_bottom_bar: ^1.2.0
  draggable_home: ^1.0.5
  cached_network_image: ^3.0.0
  dropdown_search: ^5.0.2
  google_fonts: ^6.2.1
  barcode_scan2: ^4.1.7
  permission_handler: ^10.2.0
  vertical_card_pager: ^1.6.2
  dropdown_button2: ^2.0.0
  scaled_list: ^2.0.0
  sliding_clipped_nav_bar: ^3.1.1
  flutter_custom_clippers: ^2.1.0
  wechat_camera_picker: ^4.3.1
  flutter_slider_drawer: ^2.1.3
  flutter_pdfview: ^1.2.7
  pdf: ^3.11.0
  url_launcher: ^6.2.5
  flutter_cached_pdfview: ^0.4.2
  pdfx: ^2.6.0
  webview_flutter: ^3.0.0
  dio: ^5.0.0
  path_provider: ^2.0.11
  open_file: ^3.3.2
  animated_custom_dropdown: ^3.1.1
  youtube_player_flutter: ^8.1.2
  pod_player: ^0.2.2
  flutter_gradient_app_bar: ^0.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ogm_logo2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/company-scaled.jpg
    - assets/images/logo_trandar.jpg
    - assets/images/cartoon-man.jpg
    - assets/images/ogm_logo.jpg
    - assets/images/advance.jpg
    - assets/images/asset.jpg
    - assets/images/expense.jpg
    - assets/images/product.jpg
    - assets/images/purchase.jpg
    - assets/images/person/person1.jpg
    - assets/images/person/person2.jpg
    - assets/images/person/person3.jpg
    - assets/images/person/person4.jpg
    - assets/images/person/person5.jpg
    - assets/images/person/person6.jpg
    - assets/images/person/person7.jpg
    - assets/images/logoOrigami/default_bg.png
    - assets/images/logoOrigami/ogm_logo.png
    - assets/images/celebrity/bella1.jpg
    - assets/images/celebrity/bella2.jpg
    - assets/images/celebrity/bella3.jpg
    - assets/images/celebrity/bella4.jpg
    - assets/images/celebrity/bella5.jpg
    - assets/images/celebrity/bella6.jpg
    - assets/images/logoOrigami/origami_logo.png
    - assets/ogm_logo2.png
    - assets/images/iconsNeed/advanceN.jpg
    - assets/images/iconsNeed/assetN.jpg
    - assets/images/iconsNeed/expenseN.jpg
    - assets/images/iconsNeed/productN.jpg
    - assets/images/iconsNeed/purchaseN.jpg
    - assets/images/person/19777.jpg
    - assets/images/certificate_1.png
    - assets/images/logoOrigami/allable_logo.png
    - assets/images/logoOrigami/trandar_logo.png
    - assets/images/logoOrigami/netizen_logo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: Roboto
    fonts:
      - asset: fonts/roboto/Roboto-Black.ttf
      - asset: fonts/roboto/Roboto-BlackItalic.ttf
      - asset: fonts/roboto/Roboto-Bold.ttf
      - asset: fonts/roboto/Roboto-BoldItalic.ttf
      - asset: fonts/roboto/Roboto-Italic.ttf
      - asset: fonts/roboto/Roboto-Light.ttf
      - asset: fonts/roboto/Roboto-LightItalic.ttf
      - asset: fonts/roboto/Roboto-Medium.ttf
      - asset: fonts/roboto/Roboto-MediumItalic.ttf
      - asset: fonts/roboto/Roboto-Regular.ttf
      - asset: fonts/roboto/Roboto-Thin.ttf
      - asset: fonts/roboto/Roboto-ThinItalic.ttf
        weight: 400
        style: italic
  - family: Sans
    fonts:
      - asset: fonts/noto_sans/NotoSans-Italic-VariableFont_wdth,wght.ttf
      - asset: fonts/noto_sans/NotoSans-VariableFont_wdth,wght.ttf
        weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
